config/routes.rb
Rails.application.routes.draw do
  get "top/main"
  post "top/login"
  get "top/logout"
  
  resources :users
  resources :tweets
  resources :likes
  
  root "tweets#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])
        tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render "login_form"  
  end
  
  def login
    if User.find_by(uid: params[:uid]) and User.find_by(pass: params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to tweets_path
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
    Tweet.create(message: params[:tweet][:message], user_id: 5)
    redirect_to tweets_path
  end
  
  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    User.create(uid: params[:user][:uid], 
      pass: params[:user][:pass])
    redirect_to users_path
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login_form.html.erb
<%= form_with url: '/top/login', method: :post, local: true do |f| %>
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass %>
    <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
    <%= e.message %>
    <%= e.like_users.count %>
    <%= link_to '削除', tweet_path(e), data: {turbo_method: :delete} %>
    
    <% if session[:login_uid] %>
        <%= link_to 'いいね', likes_path(tweet_id: e.id), data: { turbo_method: :post } %>
        <%= link_to 'いいね削除', like_path(e), data: { turbo_method: :delete } %>
    <% end %>
<br>
<% end %>

<%= link_to "新規追加", new_tweet_path %><br>
<%= link_to "ログイン", top_main_path %><br>
<%= link_to "ログアウト", top_logout_path %><br>
ログイン中UID：<%= session[:login_uid] %>

app/views/tweets/new.html.erb
<%= form_with model: @tweet do |f| %>
  <%= f.label :message, 'つぶやき' %>
  <%= f.text_field :message %>
  <%= f.submit 'ツイート' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <%= e.uid %>
    <%= e.pass %>
    <%= link_to '削除', user_path(e), data: {turbo_method: :delete} %>
<br>
<% end %>

<%= link_to "新規追加", new_user_path %>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <%= f.label :uid, 'UID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'PASS' %>
  <%= f.text_field :pass %>
  <%= f.submit '登録' %>
<% end %>